import { cva, type VariantProps } from "cva";

export const TypographyVariantTypeTagMap: Record<
  Exclude<TypographyVariantType, null | undefined>,
  keyof JSX.IntrinsicElements
> = {
  "display-l": "h1",
  "display-m": "h2",
  "display-s": "h3",
  "headline-l": "h4",
  "headline-m": "h5",
  "headline-s": "h6",
  "title-l": "h4",
  "title-m": "h5",
  "title-s": "h6",
  "body-l": "p",
  "body-m": "p",
  "body-s": "p",
  "label-l": "span",
  "label-l-bold": "span",
  "label-m": "span",
  "label-m-bold": "span",
  "label-s": "span",
  "sr-only": "span",
};

export type TypographyVariantType = VariantProps<
  typeof typographyVariants
>["variant"];

/** @deprecated use tailwind classes instead */
export const typographyVariants = cva("", {
  variants: {
    variant: {
      "display-l": "display-l",
      "display-m": "display-m",
      "display-s": "display-s",
      "headline-l": "headline-l",
      "headline-m": "headline-m",
      "headline-s": "headline-s",
      "title-l": "title-l",
      "title-m": "title-m",
      "title-s": "title-s",
      "body-l": "body-l",
      "body-m": "body-m",
      "body-s": "body-s",
      "label-l": "label-l",
      "label-l-bold": "label-l-bold",
      "label-m": "label-m",
      "label-m-bold": "label-m-bold",
      "label-s": "label-s",
      "sr-only": "sr-only",
    },
    // Maybe a better way to do this, whitelist classes and function with sm:${variable} ??
    sm: {
      "display-l": "sm:display-l",
      "display-m": "sm:display-m",
      "display-s": "sm:display-s",
      "headline-l": "sm:headline-l",
      "headline-m": "sm:headline-m",
      "headline-s": "sm:headline-s",
      "title-l": "sm:title-l",
      "title-m": "sm:title-m",
      "title-s": "sm:title-s",
      "body-l": "sm:body-l",
      "body-m": "sm:body-m",
      "body-s": "sm:body-s",
      "label-l": "sm:label-l",
      "label-l-bold": "sm:label-l-bold",
      "label-m": "sm:label-m",
      "label-m-bold": "sm:label-m-bold",
      "label-s": "sm:label-s",
      "sr-only": "sm:sr-only",
    },
    md: {
      "display-l": "md:display-l",
      "display-m": "md:display-m",
      "display-s": "md:display-s",
      "headline-l": "md:headline-l",
      "headline-m": "md:headline-m",
      "headline-s": "md:headline-s",
      "title-l": "md:title-l",
      "title-m": "md:title-m",
      "title-s": "md:title-s",
      "body-l": "md:body-l",
      "body-m": "md:body-m",
      "body-s": "md:body-s",
      "label-l": "md:label-l",
      "label-l-bold": "md:label-l-bold",
      "label-m": "md:label-m",
      "label-m-bold": "md:label-m-bold",
      "label-s": "md:label-s",
      "sr-only": "md:sr-only",
    },
    lg: {
      "display-l": "lg:display-l",
      "display-m": "lg:display-m",
      "display-s": "lg:display-s",
      "headline-l": "lg:headline-l",
      "headline-m": "lg:headline-m",
      "headline-s": "lg:headline-s",
      "title-l": "lg:title-l",
      "title-m": "lg:title-m",
      "title-s": "lg:title-s",
      "body-l": "lg:body-l",
      "body-m": "lg:body-m",
      "body-s": "lg:body-s",
      "label-l": "lg:label-l",
      "label-l-bold": "lg:label-l-bold",
      "label-m": "lg:label-m",
      "label-m-bold": "lg:label-m-bold",
      "label-s": "lg:label-s",
      "sr-only": "lg:sr-only",
    },
    xl: {
      "display-l": "xl:display-l",
      "display-m": "xl:display-m",
      "display-s": "xl:display-s",
      "headline-l": "xl:headline-l",
      "headline-m": "xl:headline-m",
      "headline-s": "xl:headline-s",
      "title-l": "xl:title-l",
      "title-m": "xl:title-m",
      "title-s": "xl:title-s",
      "body-l": "xl:body-l",
      "body-m": "xl:body-m",
      "body-s": "xl:body-s",
      "label-l": "xl:label-l",
      "label-l-bold": "xl:label-l-bold",
      "label-m": "xl:label-m",
      "label-m-bold": "xl:label-m-bold",
      "label-s": "xl:label-s",
      "sr-only": "xl:sr-only",
    },
    "2xl": {
      "display-l": "2xl:display-l",
      "display-m": "2xl:display-m",
      "display-s": "2xl:display-s",
      "headline-l": "2xl:headline-l",
      "headline-m": "2xl:headline-m",
      "headline-s": "2xl:headline-s",
      "title-l": "2xl:title-l",
      "title-m": "2xl:title-m",
      "title-s": "2xl:title-s",
      "body-l": "2xl:body-l",
      "body-m": "2xl:body-m",
      "body-s": "2xl:body-s",
      "label-l": "2xl:label-l",
      "label-l-bold": "2xl:label-l-bold",
      "label-m": "2xl:label-m",
      "label-m-bold": "2xl:label-m-bold",
      "label-s": "2xl:label-s",
      "sr-only": "2xl:sr-only",
    },
    "3xl": {
      "display-l": "3xl:display-l",
      "display-m": "3xl:display-m",
      "display-s": "3xl:display-s",
      "headline-l": "3xl:headline-l",
      "headline-m": "3xl:headline-m",
      "headline-s": "3xl:headline-s",
      "title-l": "3xl:title-l",
      "title-m": "3xl:title-m",
      "title-s": "3xl:title-s",
      "body-l": "3xl:body-l",
      "body-m": "3xl:body-m",
      "body-s": "3xl:body-s",
      "label-l": "3xl:label-l",
      "label-l-bold": "3xl:label-l-bold",
      "label-m": "3xl:label-m",
      "label-m-bold": "3xl:label-m-bold",
      "label-s": "3xl:label-s",
      "sr-only": "3xl:sr-only",
    },
    "4xl": {
      "display-l": "4xl:display-l",
      "display-m": "4xl:display-m",
      "display-s": "4xl:display-s",
      "headline-l": "4xl:headline-l",
      "headline-m": "4xl:headline-m",
      "headline-s": "4xl:headline-s",
      "title-l": "4xl:title-l",
      "title-m": "4xl:title-m",
      "title-s": "4xl:title-s",
      "body-l": "4xl:body-l",
      "body-m": "4xl:body-m",
      "body-s": "4xl:body-s",
      "label-l": "4xl:label-l",
      "label-l-bold": "4xl:label-l-bold",
      "label-m": "4xl:label-m",
      "label-m-bold": "4xl:label-m-bold",
      "label-s": "4xl:label-s",
      "sr-only": "4xl:sr-only",
    },
    display: {
      inline: "inline",
      block: "block",
    },
    align: {
      left: "text-left",
      center: "text-center",
      right: "text-right",
    },
  },
  defaultVariants: {
    variant: "body-m",
    align: "left",
  },
});
